# Workflow rescrito para utilizar o workflow Reutilizável

name: CI via Workflow Reutilizável

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  login:
    uses: profjguilherme-fatec/php-workflows/.github/workflows/login.yml@master
